/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Reports whether the process is running. Never checks dependencies.
         */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Reports whether the service can accept traffic. Runs every registered dependency check.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Verifies the credentials and starts a session. The response never reveals whether the
         *     email exists or the account is temporarily locked after repeated failures.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the session tokens
         * @description Exchanges the refresh cookie for a new access and refresh token. Each refresh token
         *     works once; presenting a used one again revokes every session of the account.
         *     `409` means a concurrent request already rotated the token: retry the original
         *     request with the cookies it set.
         */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Revokes the current session and clears the cookies. Idempotent.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current admin */
        get: operations["getCurrentAdmin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change password
         * @description Changes the password, signs out every other session and starts a fresh one for the
         *     caller (new cookies are set).
         */
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List images
         * @description Newest first. Pass `nextCursor` from the previous page as `cursor`.
         */
        get: operations["listMedia"];
        put?: never;
        /**
         * Upload an image
         * @description Accepts JPEG, PNG or WebP, identified from the file content rather than its name.
         *     The original is not stored: responsive WebP variants (480, 960 and 1600 px wide, never
         *     upscaled) are rendered with EXIF orientation applied and all metadata except the colour
         *     profile removed. Uploading the same file again returns the existing image with `200`.
         */
        post: operations["uploadMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/media/{mediaId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaId: components["parameters"]["MediaId"];
            };
            cookie?: never;
        };
        /** Get an image */
        get: operations["getMedia"];
        put?: never;
        post?: never;
        /**
         * Delete an image
         * @description Fails with `409` while the image is used by any content.
         */
        delete: operations["deleteMedia"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/media/{mediaId}/alt-text": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaId: components["parameters"]["MediaId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Replace the alternative text
         * @description Sets the alt text per language; languages left out are cleared.
         */
        put: operations["updateMediaAltText"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/media/{file}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Image variant
         * @description Serves a variant by its content-hash file name. The bytes behind a name never change,
         *     so responses are cacheable forever (`immutable`).
         */
        get: operations["getPublicMedia"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the profile
         * @description `404` until the profile is saved for the first time.
         */
        get: operations["getProfile"];
        /**
         * Replace the profile
         * @description Full replacement: optional fields left out are cleared, and so are languages missing
         *     from `translations`. Phone numbers are accepted in international notation
         *     (`+966 12 545 6789`, `00966…`) and stored in E.164.
         */
        put: operations["updateProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The published business card
         * @description Texts are in the requested language, falling back to English, Indonesian, then Arabic;
         *     `locale` tells which one was used. `404` while the profile is incomplete, so visitors
         *     see a placeholder instead of half-filled contact details.
         */
        get: operations["getPublicProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/profile/vcard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download the contact card
         * @description vCard 3.0 (UTF-8, CRLF, folded lines) with the contact card photo (the portrait unless
         *     another image is chosen) embedded as a JPEG, which both iOS Contacts and Google Contacts
         *     import. Same availability as the public profile.
         */
        get: operations["getProfileVCard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/profile/business-card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download the business card image
         * @description The uploaded business card as a JPEG (at most 1600 px wide, transparency on white), saved
         *     under the profile's name. `404` until the profile is published with a business card.
         *     The `ETag` follows the image, so a new card is fetched as soon as it is chosen.
         */
        get: operations["getProfileBusinessCard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/discover/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the topics with their documents
         * @description In display order; documents within a topic too.
         */
        get: operations["listDiscoverSections"];
        put?: never;
        /**
         * Add a topic
         * @description The new topic goes last. A title in at least one language is required.
         */
        post: operations["createDiscoverSection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/discover/section-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Reorder the topics
         * @description `ids` must list every topic exactly once, in the new order.
         */
        put: operations["reorderDiscoverSections"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/discover/sections/{sectionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sectionId: components["parameters"]["SectionId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Replace a topic's texts
         * @description Languages missing from `translations` are removed.
         */
        put: operations["updateDiscoverSection"];
        post?: never;
        /** Delete a topic and its documents */
        delete: operations["deleteDiscoverSection"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/discover/sections/{sectionId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sectionId: components["parameters"]["SectionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a PDF to a topic
         * @description `metadata` (JSON, `DocumentInput`) describes the file; `file` is the PDF, identified from
         *     its content rather than its name. The document goes last within the topic.
         */
        post: operations["uploadDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Replace a document's titles and language */
        put: operations["updateDocument"];
        post?: never;
        /** Delete a document */
        delete: operations["deleteDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/documents/{documentId}/file": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Upload a new version of the PDF
         * @description Titles, language and position stay; the public link keeps working.
         */
        put: operations["replaceDocumentFile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        /**
         * The PDF
         * @description Opens in the browser's viewer, or is saved under its file name with `download=true`.
         *     The `ETag` is the file's SHA-256, so a new version is fetched as soon as it is uploaded.
         */
        get: operations["getPublicDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the site settings
         * @description Defaults until saved for the first time.
         */
        get: operations["getSettings"];
        /** Replace the site settings */
        put: operations["updateSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/site": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Everything the public site shows
         * @description The published profile (absent until complete), the Discover topics with their documents
         *     and the virtual tour link (absent until set), in the requested language with the same
         *     fallback as the profile. Topics and documents without any text are left out.
         */
        get: operations["getPublicSite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        HealthStatus: "up" | "down";
        HealthReport: {
            status: components["schemas"]["HealthStatus"];
            /**
             * @description Build version of the running binary
             * @example 0.1.0
             */
            version: string;
            checks?: components["schemas"]["HealthCheck"][];
        };
        HealthCheck: {
            /** @example database */
            name: string;
            status: components["schemas"]["HealthStatus"];
            /** @description Failure reason; present only when status is `down` */
            error?: string;
        };
        /** @description RFC 9457 Problem Details */
        Problem: {
            /**
             * @description URI reference identifying the problem type
             * @example about:blank
             */
            type: string;
            /** @example Not Found */
            title: string;
            /**
             * Format: int32
             * @example 404
             */
            status: number;
            detail?: string;
            instance?: string;
            /** @description Correlates the response with server logs */
            requestId?: string;
            /** @description Field-level validation errors */
            errors?: components["schemas"]["FieldError"][];
        };
        FieldError: {
            /** @example checkOut */
            field: string;
            /** @example must be after checkIn */
            message: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @example momen@example.com
             */
            email: string;
            /** Format: password */
            password: string;
        };
        ChangePasswordRequest: {
            /** Format: password */
            currentPassword: string;
            /**
             * Format: password
             * @description 12–128 characters, different from the current password and the email
             */
            newPassword: string;
        };
        AdminUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            /** Format: date-time */
            lastLoginAt?: string;
            /** Format: date-time */
            passwordChangedAt: string;
        };
        SessionInfo: {
            /**
             * Format: date-time
             * @description When to refresh; the access cookie stops being sent after this instant
             */
            accessTokenExpiresAt: string;
        };
        LoginResponse: {
            admin: components["schemas"]["AdminUser"];
            /** Format: date-time */
            accessTokenExpiresAt: string;
        };
        /** @description Alternative text per interface language */
        LocalizedAltText: {
            en?: components["schemas"]["AltText"];
            id?: components["schemas"]["AltText"];
            ar?: components["schemas"]["AltText"];
        };
        AltText: string;
        ImageVariant: {
            /** Format: int32 */
            width: number;
            /** Format: int32 */
            height: number;
            /**
             * @description Immutable URL; relative to the API origin unless a CDN base is configured
             * @example /api/v1/public/media/9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08.webp
             */
            url: string;
            /** Format: int64 */
            byteSize: number;
        };
        Media: {
            /** Format: uuid */
            id: string;
            /**
             * Format: int32
             * @description Display width after EXIF orientation
             */
            width: number;
            /** Format: int32 */
            height: number;
            /** @enum {string} */
            sourceType: "image/jpeg" | "image/png" | "image/webp";
            /** Format: int64 */
            sourceBytes: number;
            originalFilename: string;
            /** @description Tiny blurred WebP data URI to show while the image loads */
            placeholder: string;
            altText: components["schemas"]["LocalizedAltText"];
            /** @description Ascending by width; use as `srcset` */
            variants: components["schemas"]["ImageVariant"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        MediaPage: {
            items: components["schemas"]["Media"][];
            /** @description Present when more images exist */
            nextCursor?: string;
        };
        /**
         * @description Interface language
         * @enum {string}
         */
        Locale: "en" | "id" | "ar";
        /**
         * @description ISO 639-1 code of a language the sales manager speaks
         * @enum {string}
         */
        SpokenLanguage: "ar" | "en" | "tr" | "id" | "ms" | "ur" | "fa" | "fr" | "de" | "es" | "it" | "nl" | "pt" | "ru" | "zh" | "ja" | "ko" | "hi" | "bn" | "ta" | "ml" | "th" | "tl" | "ha" | "so" | "sw" | "am" | "az" | "kk" | "uz" | "ky" | "tg" | "ps" | "sq" | "bs" | "ku" | "yo" | "wo";
        ProfileTranslation: {
            /** @example Director of Sales */
            title: string;
            /** @description One-line slogan under the name */
            tagline?: string;
            bio?: string;
            /** @description Text pre-filled in WhatsApp when a visitor starts a chat */
            whatsappMessage?: string;
            /**
             * @description The full name as written in this language; defaults to first and last name
             * @example مؤمن توفيق الكسواني
             */
            displayName?: string;
            address?: components["schemas"]["Address"];
        };
        /** @description Office address as written in one language */
        Address: {
            /** @example Ibrahim Al Khalil Street */
            street?: string;
            /** @example Makkah */
            city?: string;
            /** @example Saudi Arabia */
            country?: string;
        };
        /** @description Texts per interface language; at least one language is needed to publish */
        LocalizedProfileText: {
            en?: components["schemas"]["ProfileTranslation"];
            id?: components["schemas"]["ProfileTranslation"];
            ar?: components["schemas"]["ProfileTranslation"];
        };
        ProfileInput: {
            firstName: string;
            lastName?: string;
            /** @example Sheraton Makkah Jabal Al Kaaba Hotel */
            organization?: string;
            /**
             * Format: uuid
             * @description An image from the media library
             */
            portraitMediaId?: string;
            /**
             * Format: uuid
             * @description Image saved with the downloaded contact card; the portrait when left out
             */
            vcardPhotoMediaId?: string;
            /**
             * Format: uuid
             * @description The designed business card visitors save as an image
             */
            businessCardMediaId?: string;
            /** @example +966 12 545 6789 */
            phone?: string;
            whatsapp?: string;
            email?: string;
            /** @description Spoken languages in display order; defaults to Arabic, English, Turkish */
            languages?: components["schemas"]["SpokenLanguage"][];
            /** @example 24231 */
            postalCode?: string;
            /** @description https link to the office on a map */
            mapUrl?: string;
            /** @description https link to a linkedin.com page */
            linkedinUrl?: string;
            translations: components["schemas"]["LocalizedProfileText"];
        };
        Profile: {
            firstName: string;
            lastName: string;
            fullName: string;
            organization: string;
            portrait?: components["schemas"]["Media"];
            vcardPhoto?: components["schemas"]["Media"];
            businessCard?: components["schemas"]["Media"];
            /**
             * @description E.164
             * @example +966125456789
             */
            phone?: string;
            /** @description E.164 */
            whatsapp?: string;
            email?: string;
            languages: components["schemas"]["SpokenLanguage"][];
            postalCode?: string;
            mapUrl?: string;
            linkedinUrl?: string;
            translations: components["schemas"]["LocalizedProfileText"];
            /** @description Whether the public card and vCard are published */
            complete: boolean;
            /** @description What must be added before the profile is published */
            missing: ("title" | "contact")[];
            /** Format: date-time */
            updatedAt: string;
        };
        PhoneNumber: {
            /** @example +966125456789 */
            e164: string;
            /**
             * @description International format for reading; render it left-to-right
             * @example +966 12 545 6789
             */
            display: string;
        };
        WhatsAppContact: {
            e164: string;
            display: string;
            /**
             * @description Opens a chat, with the localized greeting pre-filled when one is set
             * @example https://wa.me/966125456789?text=Hello
             */
            url: string;
        };
        PublicImage: {
            /** Format: int32 */
            width: number;
            /** Format: int32 */
            height: number;
            placeholder: string;
            /** @description Alternative text in the response language, when set */
            alt?: string;
            variants: components["schemas"]["ImageVariant"][];
        };
        PublicProfile: {
            locale: components["schemas"]["Locale"];
            firstName: string;
            lastName: string;
            fullName: string;
            /** @description The name as written in the response language */
            displayName: string;
            organization: string;
            title: string;
            tagline?: string;
            bio?: string;
            portrait?: components["schemas"]["PublicImage"];
            phone?: components["schemas"]["PhoneNumber"];
            whatsapp?: components["schemas"]["WhatsAppContact"];
            email?: string;
            languages: components["schemas"]["SpokenLanguage"][];
            address?: components["schemas"]["PublicAddress"];
            mapUrl?: string;
            linkedinUrl?: string;
            /**
             * @description Downloads the business card as a JPEG; present when one is uploaded
             * @example /api/v1/public/profile/business-card?locale=en
             */
            businessCardUrl?: string;
        };
        PublicAddress: {
            street: string;
            city: string;
            postalCode: string;
            country: string;
        };
        DiscoverSectionText: {
            /**
             * @description Short label above the title
             * @example Groups & Umrah
             */
            eyebrow?: string;
            title: string;
            /** @description Plain text; blank lines separate paragraphs */
            body?: string;
        };
        LocalizedDiscoverSectionText: {
            en?: components["schemas"]["DiscoverSectionText"];
            id?: components["schemas"]["DiscoverSectionText"];
            ar?: components["schemas"]["DiscoverSectionText"];
        };
        DiscoverSectionInput: {
            translations: components["schemas"]["LocalizedDiscoverSectionText"];
        };
        DiscoverSection: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            position: number;
            translations: components["schemas"]["LocalizedDiscoverSectionText"];
            documents: components["schemas"]["Document"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        DiscoverSectionList: {
            items: components["schemas"]["DiscoverSection"][];
        };
        SectionOrder: {
            ids: string[];
        };
        DocumentText: {
            /** @example Groups and Umrah programmes */
            title: string;
        };
        LocalizedDocumentText: {
            en?: components["schemas"]["DocumentText"];
            id?: components["schemas"]["DocumentText"];
            ar?: components["schemas"]["DocumentText"];
        };
        DocumentInput: {
            language: components["schemas"]["Locale"];
            translations: components["schemas"]["LocalizedDocumentText"];
        };
        Document: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sectionId: string;
            language: components["schemas"]["Locale"];
            /** @example Groups-and-Umrah.pdf */
            fileName: string;
            /** Format: int64 */
            byteSize: number;
            /**
             * Format: int32
             * @description Absent when it cannot be read from the file
             */
            pageCount?: number;
            translations: components["schemas"]["LocalizedDocumentText"];
            /**
             * @description Opens the PDF in the browser; relative to the API origin
             * @example /api/v1/public/documents/0b0c6c1e-6b8e-4c2e-9d1a-2d9f8c3b7a10
             */
            url: string;
            /** @description Saves the PDF under `fileName` */
            downloadUrl: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SettingsInput: {
            /** @description https link to the 360° virtual tour; the tour section is hidden without it */
            tourUrl?: string;
        };
        Settings: {
            tourUrl?: string;
            /**
             * Format: date-time
             * @description Zero time until saved for the first time
             */
            updatedAt: string;
        };
        PublicDocument: {
            /** Format: uuid */
            id: string;
            title: string;
            language: components["schemas"]["Locale"];
            fileName: string;
            /** Format: int64 */
            byteSize: number;
            /** Format: int32 */
            pageCount?: number;
            url: string;
            downloadUrl: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PublicDiscoverSection: {
            /** Format: uuid */
            id: string;
            eyebrow: string;
            title: string;
            body: string;
            documents: components["schemas"]["PublicDocument"][];
        };
        PublicTour: {
            url: string;
        };
        PublicSite: {
            locale: components["schemas"]["Locale"];
            profile?: components["schemas"]["PublicProfile"];
            sections: components["schemas"]["PublicDiscoverSection"][];
            tour?: components["schemas"]["PublicTour"];
        };
    };
    responses: {
        /** @description Error response (RFC 9457) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Preferred interface language */
        LocaleQuery: components["schemas"]["Locale"];
        MediaId: string;
        SectionId: string;
        DocumentId: string;
    };
    requestBodies: never;
    headers: {
        /** @description Access and refresh token cookies (HttpOnly, SameSite=Strict) */
        SessionCookies: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReport"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All dependency checks passed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReport"];
                };
            };
            /** @description At least one dependency check failed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReport"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in; session cookies are set */
            200: {
                headers: {
                    "Set-Cookie": components["headers"]["SessionCookies"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tokens rotated; session cookies are set */
            200: {
                headers: {
                    "Set-Cookie": components["headers"]["SessionCookies"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out; session cookies are cleared */
            204: {
                headers: {
                    "Set-Cookie": components["headers"]["SessionCookies"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getCurrentAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in admin */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            401: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed; new session cookies are set */
            204: {
                headers: {
                    "Set-Cookie": components["headers"]["SessionCookies"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listMedia: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of images */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    uploadMedia: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description The same file was uploaded before; the existing image is returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Media"];
                };
            };
            /** @description Image stored */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Media"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaId: components["parameters"]["MediaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Media"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    deleteMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaId: components["parameters"]["MediaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    updateMediaAltText: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaId: components["parameters"]["MediaId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocalizedAltText"];
            };
        };
        responses: {
            /** @description Updated image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Media"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getPublicMedia: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: string;
            };
            path: {
                file: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The image */
            200: {
                headers: {
                    /** @example public, max-age=31536000, immutable */
                    "Cache-Control"?: string;
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "image/webp": string;
                };
            };
            /** @description The client copy is current */
            304: {
                headers: {
                    "Cache-Control"?: string;
                    ETag?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The profile, with what is still missing before it can be published */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileInput"];
            };
        };
        responses: {
            /** @description The saved profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getPublicProfile: {
        parameters: {
            query?: {
                /** @description Preferred interface language */
                locale?: components["parameters"]["LocaleQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The business card */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicProfile"];
                };
            };
            400: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getProfileVCard: {
        parameters: {
            query?: {
                /** @description Preferred interface language */
                locale?: components["parameters"]["LocaleQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The contact card */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/vcard": string;
                };
            };
            400: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getProfileBusinessCard: {
        parameters: {
            query?: {
                /** @description Preferred interface language */
                locale?: components["parameters"]["LocaleQuery"];
            };
            header?: {
                "If-None-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The business card */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    ETag?: string;
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
            /** @description The client copy is current */
            304: {
                headers: {
                    "Cache-Control"?: string;
                    ETag?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listDiscoverSections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All topics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverSectionList"];
                };
            };
            401: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    createDiscoverSection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoverSectionInput"];
            };
        };
        responses: {
            /** @description Topic created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverSection"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    reorderDiscoverSections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SectionOrder"];
            };
        };
        responses: {
            /** @description All topics in the new order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverSectionList"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    updateDiscoverSection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sectionId: components["parameters"]["SectionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoverSectionInput"];
            };
        };
        responses: {
            /** @description The saved topic */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverSection"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    deleteDiscoverSection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sectionId: components["parameters"]["SectionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    uploadDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sectionId: components["parameters"]["SectionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    metadata: components["schemas"]["DocumentInput"];
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Document stored */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    updateDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentInput"];
            };
        };
        responses: {
            /** @description The saved document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    deleteDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    replaceDocumentFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description The updated document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getPublicDocument: {
        parameters: {
            query?: {
                download?: boolean;
            };
            header?: {
                "If-None-Match"?: string;
            };
            path: {
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The PDF */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    ETag?: string;
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            /** @description The client copy is current */
            304: {
                headers: {
                    "Cache-Control"?: string;
                    ETag?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            401: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsInput"];
            };
        };
        responses: {
            /** @description The saved settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getPublicSite: {
        parameters: {
            query?: {
                /** @description Preferred interface language */
                locale?: components["parameters"]["LocaleQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The site content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicSite"];
                };
            };
            400: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
}
