/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Reports whether the process is running. Never checks dependencies.
         */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Reports whether the service can accept traffic. Runs every registered dependency check.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        HealthStatus: "up" | "down";
        HealthReport: {
            status: components["schemas"]["HealthStatus"];
            /**
             * @description Build version of the running binary
             * @example 0.1.0
             */
            version: string;
            checks?: components["schemas"]["HealthCheck"][];
        };
        HealthCheck: {
            /** @example database */
            name: string;
            status: components["schemas"]["HealthStatus"];
            /** @description Failure reason; present only when status is `down` */
            error?: string;
        };
        /** @description RFC 9457 Problem Details */
        Problem: {
            /**
             * @description URI reference identifying the problem type
             * @example about:blank
             */
            type: string;
            /** @example Not Found */
            title: string;
            /**
             * Format: int32
             * @example 404
             */
            status: number;
            detail?: string;
            instance?: string;
            /** @description Correlates the response with server logs */
            requestId?: string;
            /** @description Field-level validation errors */
            errors?: components["schemas"]["FieldError"][];
        };
        FieldError: {
            /** @example checkOut */
            field: string;
            /** @example must be after checkIn */
            message: string;
        };
    };
    responses: {
        /** @description Error response (RFC 9457) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReport"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All dependency checks passed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReport"];
                };
            };
            /** @description At least one dependency check failed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReport"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
