// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (checksum, original_filename, source_type, source_bytes, width, height, placeholder)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, checksum, original_filename, source_type, source_bytes, width, height, placeholder, created_at, updated_at
`

type CreateMediaParams struct {
	Checksum         []byte
	OriginalFilename string
	SourceType       string
	SourceBytes      int64
	Width            int32
	Height           int32
	Placeholder      string
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Media, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.Checksum,
		arg.OriginalFilename,
		arg.SourceType,
		arg.SourceBytes,
		arg.Width,
		arg.Height,
		arg.Placeholder,
	)
	var i Media
	err := row.Scan(
		&i.ID,
		&i.Checksum,
		&i.OriginalFilename,
		&i.SourceType,
		&i.SourceBytes,
		&i.Width,
		&i.Height,
		&i.Placeholder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTranslation = `-- name: CreateTranslation :exec
INSERT INTO media_translations (media_id, locale, alt_text) VALUES ($1, $2, $3)
`

type CreateTranslationParams struct {
	MediaID uuid.UUID
	Locale  string
	AltText string
}

func (q *Queries) CreateTranslation(ctx context.Context, arg CreateTranslationParams) error {
	_, err := q.db.Exec(ctx, createTranslation, arg.MediaID, arg.Locale, arg.AltText)
	return err
}

const createVariant = `-- name: CreateVariant :exec
INSERT INTO media_variants (media_id, width, height, storage_key, byte_size)
VALUES ($1, $2, $3, $4, $5)
`

type CreateVariantParams struct {
	MediaID    uuid.UUID
	Width      int32
	Height     int32
	StorageKey string
	ByteSize   int64
}

func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) error {
	_, err := q.db.Exec(ctx, createVariant,
		arg.MediaID,
		arg.Width,
		arg.Height,
		arg.StorageKey,
		arg.ByteSize,
	)
	return err
}

const deleteMedia = `-- name: DeleteMedia :execrows
DELETE FROM media WHERE id = $1
`

func (q *Queries) DeleteMedia(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMedia, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTranslations = `-- name: DeleteTranslations :exec
DELETE FROM media_translations WHERE media_id = $1
`

func (q *Queries) DeleteTranslations(ctx context.Context, mediaID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTranslations, mediaID)
	return err
}

const getMedia = `-- name: GetMedia :one
SELECT id, checksum, original_filename, source_type, source_bytes, width, height, placeholder, created_at, updated_at FROM media WHERE id = $1
`

func (q *Queries) GetMedia(ctx context.Context, id uuid.UUID) (Media, error) {
	row := q.db.QueryRow(ctx, getMedia, id)
	var i Media
	err := row.Scan(
		&i.ID,
		&i.Checksum,
		&i.OriginalFilename,
		&i.SourceType,
		&i.SourceBytes,
		&i.Width,
		&i.Height,
		&i.Placeholder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMediaByChecksum = `-- name: GetMediaByChecksum :one
SELECT id, checksum, original_filename, source_type, source_bytes, width, height, placeholder, created_at, updated_at FROM media WHERE checksum = $1
`

func (q *Queries) GetMediaByChecksum(ctx context.Context, checksum []byte) (Media, error) {
	row := q.db.QueryRow(ctx, getMediaByChecksum, checksum)
	var i Media
	err := row.Scan(
		&i.ID,
		&i.Checksum,
		&i.OriginalFilename,
		&i.SourceType,
		&i.SourceBytes,
		&i.Width,
		&i.Height,
		&i.Placeholder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariantByKey = `-- name: GetVariantByKey :one
SELECT storage_key, content_type, byte_size FROM media_variants WHERE storage_key = $1
`

type GetVariantByKeyRow struct {
	StorageKey  string
	ContentType string
	ByteSize    int64
}

func (q *Queries) GetVariantByKey(ctx context.Context, storageKey string) (GetVariantByKeyRow, error) {
	row := q.db.QueryRow(ctx, getVariantByKey, storageKey)
	var i GetVariantByKeyRow
	err := row.Scan(&i.StorageKey, &i.ContentType, &i.ByteSize)
	return i, err
}

const listMedia = `-- name: ListMedia :many
SELECT id, checksum, original_filename, source_type, source_bytes, width, height, placeholder, created_at, updated_at FROM media
WHERE $1::timestamptz IS NULL
   OR (created_at, id) < ($1::timestamptz, $2::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListMediaParams struct {
	AfterCreatedAt *time.Time
	AfterID        *uuid.UUID
	PageSize       int32
}

// Keyset pagination: pass the last row's (created_at, id) to get the next page.
func (q *Queries) ListMedia(ctx context.Context, arg ListMediaParams) ([]Media, error) {
	rows, err := q.db.Query(ctx, listMedia, arg.AfterCreatedAt, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Media{}
	for rows.Next() {
		var i Media
		if err := rows.Scan(
			&i.ID,
			&i.Checksum,
			&i.OriginalFilename,
			&i.SourceType,
			&i.SourceBytes,
			&i.Width,
			&i.Height,
			&i.Placeholder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranslations = `-- name: ListTranslations :many
SELECT media_id, locale, alt_text FROM media_translations WHERE media_id = ANY($1::uuid[]) ORDER BY media_id, locale
`

func (q *Queries) ListTranslations(ctx context.Context, mediaIds []uuid.UUID) ([]MediaTranslation, error) {
	rows, err := q.db.Query(ctx, listTranslations, mediaIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaTranslation{}
	for rows.Next() {
		var i MediaTranslation
		if err := rows.Scan(&i.MediaID, &i.Locale, &i.AltText); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariants = `-- name: ListVariants :many
SELECT media_id, width, height, storage_key, content_type, byte_size FROM media_variants WHERE media_id = ANY($1::uuid[]) ORDER BY media_id, width
`

func (q *Queries) ListVariants(ctx context.Context, mediaIds []uuid.UUID) ([]MediaVariant, error) {
	rows, err := q.db.Query(ctx, listVariants, mediaIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaVariant{}
	for rows.Next() {
		var i MediaVariant
		if err := rows.Scan(
			&i.MediaID,
			&i.Width,
			&i.Height,
			&i.StorageKey,
			&i.ContentType,
			&i.ByteSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMedia = `-- name: LockMedia :one
SELECT id FROM media WHERE id = $1 FOR UPDATE
`

// Locks the row so the variant lookup and the delete see the same state.
func (q *Queries) LockMedia(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockMedia, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const touchMedia = `-- name: TouchMedia :execrows
UPDATE media SET updated_at = now() WHERE id = $1
`

func (q *Queries) TouchMedia(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, touchMedia, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
