// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateMedia(ctx context.Context, arg CreateMediaParams) (Media, error)
	CreateTranslation(ctx context.Context, arg CreateTranslationParams) error
	CreateVariant(ctx context.Context, arg CreateVariantParams) error
	DeleteMedia(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteTranslations(ctx context.Context, mediaID uuid.UUID) error
	GetMedia(ctx context.Context, id uuid.UUID) (Media, error)
	GetMediaByChecksum(ctx context.Context, checksum []byte) (Media, error)
	GetVariantByKey(ctx context.Context, storageKey string) (GetVariantByKeyRow, error)
	// Keyset pagination: pass the last row's (created_at, id) to get the next page.
	ListMedia(ctx context.Context, arg ListMediaParams) ([]Media, error)
	ListTranslations(ctx context.Context, mediaIds []uuid.UUID) ([]MediaTranslation, error)
	ListVariants(ctx context.Context, mediaIds []uuid.UUID) ([]MediaVariant, error)
	// Locks the row so the variant lookup and the delete see the same state.
	LockMedia(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	TouchMedia(ctx context.Context, id uuid.UUID) (int64, error)
}

var _ Querier = (*Queries)(nil)
