// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	GetSettings(ctx context.Context) (SiteSetting, error)
	UpsertSettings(ctx context.Context, tourUrl string) (SiteSetting, error)
}

var _ Querier = (*Queries)(nil)
