// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package store

import (
	"context"
)

const getSettings = `-- name: GetSettings :one
SELECT id, tour_url, created_at, updated_at FROM site_settings WHERE id = 1
`

func (q *Queries) GetSettings(ctx context.Context) (SiteSetting, error) {
	row := q.db.QueryRow(ctx, getSettings)
	var i SiteSetting
	err := row.Scan(
		&i.ID,
		&i.TourUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSettings = `-- name: UpsertSettings :one
INSERT INTO site_settings (id, tour_url)
VALUES (1, $1)
ON CONFLICT (id) DO UPDATE SET tour_url = EXCLUDED.tour_url
RETURNING id, tour_url, created_at, updated_at
`

func (q *Queries) UpsertSettings(ctx context.Context, tourUrl string) (SiteSetting, error) {
	row := q.db.QueryRow(ctx, upsertSettings, tourUrl)
	var i SiteSetting
	err := row.Scan(
		&i.ID,
		&i.TourUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
