#!/usr/bin/env bash
# Turns a video into the WebP frame sequences played by <ScrollCanvasVideo>, plus a typed
# manifest describing them.
#
#   scripts/extract-frames.sh <video> <name> <manifest.ts>
#   e.g. scripts/extract-frames.sh ~/Desktop/hero.mp4 hero src/features/home/hero-frames.gen.ts
#
# Two sets are written to public/frames/<name>-<hash>/, named after their content so they can
# be cached forever (see next.config.ts); older versions are removed:
#   landscape/  full frame, 1600 px wide, for screens wider than tall
#   portrait/   centered 3:4 crop, 1080 px tall, for phones: a portrait screen shows only the
#               middle of a landscape frame, so it gets that part at a higher resolution for
#               fewer bytes
# Requires ffmpeg with libwebp (set FFMPEG to use a specific binary).
set -euo pipefail

if [[ $# -ne 3 ]]; then
  sed -n '2,6p' "$0" >&2
  exit 2
fi

abs() { echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"; }
video=$(abs "$1") name=$2 manifest=$(abs "$3")
ffmpeg=${FFMPEG:-ffmpeg}
quality=${FRAME_QUALITY:-72}
out="public/frames/.tmp-$name"

[[ $name =~ ^[a-z0-9-]+$ ]] || { echo "name must be lowercase letters, digits and dashes" >&2; exit 2; }
cd "$(dirname "$0")/.."

rm -rf "$out"
mkdir -p "$out/landscape" "$out/portrait"

encode() {
  "$ffmpeg" -hide_banner -loglevel error -i "$video" -an -fps_mode passthrough \
    -vf "$1" -c:v libwebp -quality "$quality" -compression_level 6 -preset photo \
    "$out/$2/frame_%04d.webp"
}
encode "scale=1600:-2:flags=lanczos" landscape
encode "crop=ih*3/4:ih,scale=-2:1080:flags=lanczos" portrait

hash=$(cd "$out" && find . -type f -name '*.webp' | LC_ALL=C sort | xargs cat | shasum -a 256 | cut -c1-8)
count=$(find "$out/landscape" -name 'frame_*.webp' | wc -l | tr -d ' ')
[[ $count -eq $(find "$out/portrait" -name 'frame_*.webp' | wc -l | tr -d ' ') ]] || { echo "frame counts differ" >&2; exit 1; }

size() { "$ffmpeg" -hide_banner -i "$out/$1/frame_0001.webp" 2>&1 | grep -oE '[0-9]{2,5}x[0-9]{2,5}' | head -1; }
IFS=x read -r lw lh <<<"$(size landscape)"
IFS=x read -r pw ph <<<"$(size portrait)"

find public/frames -maxdepth 1 -type d -name "$name-????????" -exec rm -rf {} +
final="public/frames/$name-$hash"
mv "$out" "$final"
out=$final

cat >"$manifest" <<EOF
// Generated by scripts/extract-frames.sh — do not edit.
import type { FrameSequence } from "@/lib/frame-sequence";

export const ${name//-/_}Frames: FrameSequence = {
  basePath: "/frames/$name-$hash",
  count: $count,
  sets: {
    landscape: { width: $lw, height: $lh },
    portrait: { width: $pw, height: $ph },
  },
};
EOF

echo "$count frames → $out ($(du -sh "$out/landscape" | cut -f1) landscape, $(du -sh "$out/portrait" | cut -f1) portrait)"
