// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createTranslation = `-- name: CreateTranslation :exec
INSERT INTO profile_translations (
    profile_id, locale, title, tagline, bio, whatsapp_message, display_name, street, city, country
)
VALUES (
    1, $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type CreateTranslationParams struct {
	Locale          string
	Title           string
	Tagline         string
	Bio             string
	WhatsappMessage string
	DisplayName     string
	Street          string
	City            string
	Country         string
}

func (q *Queries) CreateTranslation(ctx context.Context, arg CreateTranslationParams) error {
	_, err := q.db.Exec(ctx, createTranslation,
		arg.Locale,
		arg.Title,
		arg.Tagline,
		arg.Bio,
		arg.WhatsappMessage,
		arg.DisplayName,
		arg.Street,
		arg.City,
		arg.Country,
	)
	return err
}

const deleteTranslations = `-- name: DeleteTranslations :exec
DELETE FROM profile_translations WHERE profile_id = 1
`

func (q *Queries) DeleteTranslations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteTranslations)
	return err
}

const getProfile = `-- name: GetProfile :one
SELECT id, first_name, last_name, organization, portrait_media_id, phone, whatsapp, email, languages, created_at, updated_at, vcard_photo_media_id, postal_code, map_url, linkedin_url FROM profile WHERE id = 1
`

func (q *Queries) GetProfile(ctx context.Context) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfile)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Organization,
		&i.PortraitMediaID,
		&i.Phone,
		&i.Whatsapp,
		&i.Email,
		&i.Languages,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VcardPhotoMediaID,
		&i.PostalCode,
		&i.MapUrl,
		&i.LinkedinUrl,
	)
	return i, err
}

const listTranslations = `-- name: ListTranslations :many
SELECT profile_id, locale, title, tagline, bio, whatsapp_message, display_name, street, city, country FROM profile_translations WHERE profile_id = 1 ORDER BY locale
`

func (q *Queries) ListTranslations(ctx context.Context) ([]ProfileTranslation, error) {
	rows, err := q.db.Query(ctx, listTranslations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProfileTranslation{}
	for rows.Next() {
		var i ProfileTranslation
		if err := rows.Scan(
			&i.ProfileID,
			&i.Locale,
			&i.Title,
			&i.Tagline,
			&i.Bio,
			&i.WhatsappMessage,
			&i.DisplayName,
			&i.Street,
			&i.City,
			&i.Country,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProfile = `-- name: UpsertProfile :one
INSERT INTO profile (
    id, first_name, last_name, organization, portrait_media_id, vcard_photo_media_id,
    phone, whatsapp, email, languages, postal_code, map_url, linkedin_url
)
VALUES (
    1, $1, $2, $3, $4, $5,
    $6, $7, $8, $9::text[], $10, $11, $12
)
ON CONFLICT (id) DO UPDATE SET
    first_name           = EXCLUDED.first_name,
    last_name            = EXCLUDED.last_name,
    organization         = EXCLUDED.organization,
    portrait_media_id    = EXCLUDED.portrait_media_id,
    vcard_photo_media_id = EXCLUDED.vcard_photo_media_id,
    phone                = EXCLUDED.phone,
    whatsapp             = EXCLUDED.whatsapp,
    email                = EXCLUDED.email,
    languages            = EXCLUDED.languages,
    postal_code          = EXCLUDED.postal_code,
    map_url              = EXCLUDED.map_url,
    linkedin_url         = EXCLUDED.linkedin_url
RETURNING id, first_name, last_name, organization, portrait_media_id, phone, whatsapp, email, languages, created_at, updated_at, vcard_photo_media_id, postal_code, map_url, linkedin_url
`

type UpsertProfileParams struct {
	FirstName         string
	LastName          string
	Organization      string
	PortraitMediaID   *uuid.UUID
	VcardPhotoMediaID *uuid.UUID
	Phone             *string
	Whatsapp          *string
	Email             *string
	Languages         []string
	PostalCode        string
	MapUrl            string
	LinkedinUrl       string
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, upsertProfile,
		arg.FirstName,
		arg.LastName,
		arg.Organization,
		arg.PortraitMediaID,
		arg.VcardPhotoMediaID,
		arg.Phone,
		arg.Whatsapp,
		arg.Email,
		arg.Languages,
		arg.PostalCode,
		arg.MapUrl,
		arg.LinkedinUrl,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Organization,
		&i.PortraitMediaID,
		&i.Phone,
		&i.Whatsapp,
		&i.Email,
		&i.Languages,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VcardPhotoMediaID,
		&i.PostalCode,
		&i.MapUrl,
		&i.LinkedinUrl,
	)
	return i, err
}
