// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createTranslation = `-- name: CreateTranslation :exec
INSERT INTO profile_translations (profile_id, locale, title, tagline, bio, whatsapp_message)
VALUES (1, $1, $2, $3, $4, $5)
`

type CreateTranslationParams struct {
	Locale          string
	Title           string
	Tagline         string
	Bio             string
	WhatsappMessage string
}

func (q *Queries) CreateTranslation(ctx context.Context, arg CreateTranslationParams) error {
	_, err := q.db.Exec(ctx, createTranslation,
		arg.Locale,
		arg.Title,
		arg.Tagline,
		arg.Bio,
		arg.WhatsappMessage,
	)
	return err
}

const deleteTranslations = `-- name: DeleteTranslations :exec
DELETE FROM profile_translations WHERE profile_id = 1
`

func (q *Queries) DeleteTranslations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteTranslations)
	return err
}

const getProfile = `-- name: GetProfile :one
SELECT id, first_name, last_name, organization, portrait_media_id, phone, whatsapp, email, languages, created_at, updated_at FROM profile WHERE id = 1
`

func (q *Queries) GetProfile(ctx context.Context) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfile)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Organization,
		&i.PortraitMediaID,
		&i.Phone,
		&i.Whatsapp,
		&i.Email,
		&i.Languages,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTranslations = `-- name: ListTranslations :many
SELECT profile_id, locale, title, tagline, bio, whatsapp_message FROM profile_translations WHERE profile_id = 1 ORDER BY locale
`

func (q *Queries) ListTranslations(ctx context.Context) ([]ProfileTranslation, error) {
	rows, err := q.db.Query(ctx, listTranslations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProfileTranslation{}
	for rows.Next() {
		var i ProfileTranslation
		if err := rows.Scan(
			&i.ProfileID,
			&i.Locale,
			&i.Title,
			&i.Tagline,
			&i.Bio,
			&i.WhatsappMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProfile = `-- name: UpsertProfile :one
INSERT INTO profile (id, first_name, last_name, organization, portrait_media_id, phone, whatsapp, email, languages)
VALUES (1, $1, $2, $3, $4, $5, $6, $7, $8::text[])
ON CONFLICT (id) DO UPDATE SET
    first_name        = EXCLUDED.first_name,
    last_name         = EXCLUDED.last_name,
    organization      = EXCLUDED.organization,
    portrait_media_id = EXCLUDED.portrait_media_id,
    phone             = EXCLUDED.phone,
    whatsapp          = EXCLUDED.whatsapp,
    email             = EXCLUDED.email,
    languages         = EXCLUDED.languages
RETURNING id, first_name, last_name, organization, portrait_media_id, phone, whatsapp, email, languages, created_at, updated_at
`

type UpsertProfileParams struct {
	FirstName       string
	LastName        string
	Organization    string
	PortraitMediaID *uuid.UUID
	Phone           *string
	Whatsapp        *string
	Email           *string
	Languages       []string
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, upsertProfile,
		arg.FirstName,
		arg.LastName,
		arg.Organization,
		arg.PortraitMediaID,
		arg.Phone,
		arg.Whatsapp,
		arg.Email,
		arg.Languages,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Organization,
		&i.PortraitMediaID,
		&i.Phone,
		&i.Whatsapp,
		&i.Email,
		&i.Languages,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
