// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CreateTranslation(ctx context.Context, arg CreateTranslationParams) error
	DeleteTranslations(ctx context.Context) error
	GetProfile(ctx context.Context) (Profile, error)
	ListTranslations(ctx context.Context) ([]ProfileTranslation, error)
	UpsertProfile(ctx context.Context, arg UpsertProfileParams) (Profile, error)
}

var _ Querier = (*Queries)(nil)
