// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discover.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (id, section_id, position, language, storage_key, file_name, byte_size, page_count, sha256)
VALUES (
    $1, $2,
    (SELECT COALESCE(MAX(position) + 1, 0) FROM documents WHERE section_id = $2),
    $3, $4, $5, $6, $7, $8
)
RETURNING id, section_id, position, language, storage_key, file_name, byte_size, page_count, sha256, created_at, updated_at
`

type CreateDocumentParams struct {
	ID         uuid.UUID
	SectionID  uuid.UUID
	Language   string
	StorageKey string
	FileName   string
	ByteSize   int64
	PageCount  *int32
	Sha256     []byte
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.ID,
		arg.SectionID,
		arg.Language,
		arg.StorageKey,
		arg.FileName,
		arg.ByteSize,
		arg.PageCount,
		arg.Sha256,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Position,
		&i.Language,
		&i.StorageKey,
		&i.FileName,
		&i.ByteSize,
		&i.PageCount,
		&i.Sha256,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDocumentTranslation = `-- name: CreateDocumentTranslation :exec
INSERT INTO document_translations (document_id, locale, title)
VALUES ($1, $2, $3)
`

type CreateDocumentTranslationParams struct {
	DocumentID uuid.UUID
	Locale     string
	Title      string
}

func (q *Queries) CreateDocumentTranslation(ctx context.Context, arg CreateDocumentTranslationParams) error {
	_, err := q.db.Exec(ctx, createDocumentTranslation, arg.DocumentID, arg.Locale, arg.Title)
	return err
}

const createSection = `-- name: CreateSection :one
INSERT INTO discover_sections (id, position)
VALUES ($1, (SELECT COALESCE(MAX(position) + 1, 0) FROM discover_sections))
RETURNING id, position, created_at, updated_at
`

func (q *Queries) CreateSection(ctx context.Context, id uuid.UUID) (DiscoverSection, error) {
	row := q.db.QueryRow(ctx, createSection, id)
	var i DiscoverSection
	err := row.Scan(
		&i.ID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSectionTranslation = `-- name: CreateSectionTranslation :exec
INSERT INTO discover_section_translations (section_id, locale, eyebrow, title, body)
VALUES ($1, $2, $3, $4, $5)
`

type CreateSectionTranslationParams struct {
	SectionID uuid.UUID
	Locale    string
	Eyebrow   string
	Title     string
	Body      string
}

func (q *Queries) CreateSectionTranslation(ctx context.Context, arg CreateSectionTranslationParams) error {
	_, err := q.db.Exec(ctx, createSectionTranslation,
		arg.SectionID,
		arg.Locale,
		arg.Eyebrow,
		arg.Title,
		arg.Body,
	)
	return err
}

const deleteDocument = `-- name: DeleteDocument :execrows
DELETE FROM documents WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDocument, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDocumentTranslations = `-- name: DeleteDocumentTranslations :exec
DELETE FROM document_translations WHERE document_id = $1
`

func (q *Queries) DeleteDocumentTranslations(ctx context.Context, documentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocumentTranslations, documentID)
	return err
}

const deleteSection = `-- name: DeleteSection :execrows
DELETE FROM discover_sections WHERE id = $1
`

func (q *Queries) DeleteSection(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSection, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSectionTranslations = `-- name: DeleteSectionTranslations :exec
DELETE FROM discover_section_translations WHERE section_id = $1
`

func (q *Queries) DeleteSectionTranslations(ctx context.Context, sectionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSectionTranslations, sectionID)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, section_id, position, language, storage_key, file_name, byte_size, page_count, sha256, created_at, updated_at FROM documents WHERE id = $1
`

func (q *Queries) GetDocument(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Position,
		&i.Language,
		&i.StorageKey,
		&i.FileName,
		&i.ByteSize,
		&i.PageCount,
		&i.Sha256,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSection = `-- name: GetSection :one
SELECT id, position, created_at, updated_at FROM discover_sections WHERE id = $1
`

func (q *Queries) GetSection(ctx context.Context, id uuid.UUID) (DiscoverSection, error) {
	row := q.db.QueryRow(ctx, getSection, id)
	var i DiscoverSection
	err := row.Scan(
		&i.ID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocumentTranslations = `-- name: ListDocumentTranslations :many
SELECT document_id, locale, title FROM document_translations ORDER BY document_id, locale
`

func (q *Queries) ListDocumentTranslations(ctx context.Context) ([]DocumentTranslation, error) {
	rows, err := q.db.Query(ctx, listDocumentTranslations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentTranslation{}
	for rows.Next() {
		var i DocumentTranslation
		if err := rows.Scan(&i.DocumentID, &i.Locale, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, section_id, position, language, storage_key, file_name, byte_size, page_count, sha256, created_at, updated_at FROM documents ORDER BY section_id, position, created_at
`

func (q *Queries) ListDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.Position,
			&i.Language,
			&i.StorageKey,
			&i.FileName,
			&i.ByteSize,
			&i.PageCount,
			&i.Sha256,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionStorageKeys = `-- name: ListSectionStorageKeys :many
SELECT storage_key FROM documents WHERE section_id = $1
`

func (q *Queries) ListSectionStorageKeys(ctx context.Context, sectionID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listSectionStorageKeys, sectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var storage_key string
		if err := rows.Scan(&storage_key); err != nil {
			return nil, err
		}
		items = append(items, storage_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionTranslations = `-- name: ListSectionTranslations :many
SELECT section_id, locale, eyebrow, title, body FROM discover_section_translations ORDER BY section_id, locale
`

func (q *Queries) ListSectionTranslations(ctx context.Context) ([]DiscoverSectionTranslation, error) {
	rows, err := q.db.Query(ctx, listSectionTranslations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiscoverSectionTranslation{}
	for rows.Next() {
		var i DiscoverSectionTranslation
		if err := rows.Scan(
			&i.SectionID,
			&i.Locale,
			&i.Eyebrow,
			&i.Title,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSections = `-- name: ListSections :many
SELECT id, position, created_at, updated_at FROM discover_sections ORDER BY position, created_at
`

func (q *Queries) ListSections(ctx context.Context) ([]DiscoverSection, error) {
	rows, err := q.db.Query(ctx, listSections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiscoverSection{}
	for rows.Next() {
		var i DiscoverSection
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDocument = `-- name: LockDocument :one
SELECT id, section_id, position, language, storage_key, file_name, byte_size, page_count, sha256, created_at, updated_at FROM documents WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockDocument(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, lockDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Position,
		&i.Language,
		&i.StorageKey,
		&i.FileName,
		&i.ByteSize,
		&i.PageCount,
		&i.Sha256,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockSections = `-- name: LockSections :many
SELECT id FROM discover_sections ORDER BY position, created_at FOR UPDATE
`

// Serialises writers that renumber positions.
func (q *Queries) LockSections(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockSections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceDocumentFile = `-- name: ReplaceDocumentFile :exec
UPDATE documents
SET storage_key = $1, file_name = $2, byte_size = $3,
    page_count = $4, sha256 = $5
WHERE id = $6
`

type ReplaceDocumentFileParams struct {
	StorageKey string
	FileName   string
	ByteSize   int64
	PageCount  *int32
	Sha256     []byte
	ID         uuid.UUID
}

func (q *Queries) ReplaceDocumentFile(ctx context.Context, arg ReplaceDocumentFileParams) error {
	_, err := q.db.Exec(ctx, replaceDocumentFile,
		arg.StorageKey,
		arg.FileName,
		arg.ByteSize,
		arg.PageCount,
		arg.Sha256,
		arg.ID,
	)
	return err
}

const setSectionPosition = `-- name: SetSectionPosition :exec
UPDATE discover_sections SET position = $1 WHERE id = $2
`

type SetSectionPositionParams struct {
	Position int32
	ID       uuid.UUID
}

func (q *Queries) SetSectionPosition(ctx context.Context, arg SetSectionPositionParams) error {
	_, err := q.db.Exec(ctx, setSectionPosition, arg.Position, arg.ID)
	return err
}

const touchSection = `-- name: TouchSection :exec
UPDATE discover_sections SET updated_at = now() WHERE id = $1
`

func (q *Queries) TouchSection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSection, id)
	return err
}

const updateDocumentLanguage = `-- name: UpdateDocumentLanguage :exec
UPDATE documents SET language = $1 WHERE id = $2
`

type UpdateDocumentLanguageParams struct {
	Language string
	ID       uuid.UUID
}

func (q *Queries) UpdateDocumentLanguage(ctx context.Context, arg UpdateDocumentLanguageParams) error {
	_, err := q.db.Exec(ctx, updateDocumentLanguage, arg.Language, arg.ID)
	return err
}
