// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	CreateDocumentTranslation(ctx context.Context, arg CreateDocumentTranslationParams) error
	CreateSection(ctx context.Context, id uuid.UUID) (DiscoverSection, error)
	CreateSectionTranslation(ctx context.Context, arg CreateSectionTranslationParams) error
	DeleteDocument(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteDocumentTranslations(ctx context.Context, documentID uuid.UUID) error
	DeleteSection(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteSectionTranslations(ctx context.Context, sectionID uuid.UUID) error
	GetDocument(ctx context.Context, id uuid.UUID) (Document, error)
	GetSection(ctx context.Context, id uuid.UUID) (DiscoverSection, error)
	ListDocumentTranslations(ctx context.Context) ([]DocumentTranslation, error)
	ListDocuments(ctx context.Context) ([]Document, error)
	ListSectionStorageKeys(ctx context.Context, sectionID uuid.UUID) ([]string, error)
	ListSectionTranslations(ctx context.Context) ([]DiscoverSectionTranslation, error)
	ListSections(ctx context.Context) ([]DiscoverSection, error)
	LockDocument(ctx context.Context, id uuid.UUID) (Document, error)
	// Serialises writers that renumber positions.
	LockSections(ctx context.Context) ([]uuid.UUID, error)
	ReplaceDocumentFile(ctx context.Context, arg ReplaceDocumentFileParams) error
	SetSectionPosition(ctx context.Context, arg SetSectionPositionParams) error
	TouchSection(ctx context.Context, id uuid.UUID) error
	UpdateDocumentLanguage(ctx context.Context, arg UpdateDocumentLanguageParams) error
}

var _ Querier = (*Queries)(nil)
