// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
)

type Querier interface {
	// Round-trips a statement through the pool; stronger than a bare connection ping.
	Ping(ctx context.Context) (int32, error)
}

var _ Querier = (*Queries)(nil)
