// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package store

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const countAdmins = `-- name: CountAdmins :one
SELECT count(*) FROM admin_users
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admin_users (email, password_hash, password_changed_at)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, password_changed_at, failed_login_count, locked_until, last_login_at, created_at, updated_at
`

type CreateAdminParams struct {
	Email        string
	PasswordHash string
	Now          time.Time
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, createAdmin, arg.Email, arg.PasswordHash, arg.Now)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (session_id, token_hash, expires_at, created_at)
VALUES ($1, $2, $3, $4)
`

type CreateRefreshTokenParams struct {
	SessionID uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	Now       time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.SessionID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Now,
	)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO auth_sessions (user_id, created_at, last_seen_at, expires_at, ip, user_agent)
VALUES ($1, $2, $2, $3, $4, $5)
RETURNING id, user_id, created_at, last_seen_at, expires_at, revoked_at, revoke_reason, ip, user_agent
`

type CreateSessionParams struct {
	UserID    uuid.UUID
	Now       time.Time
	ExpiresAt time.Time
	Ip        *netip.Addr
	UserAgent *string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.Now,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.Ip,
		&i.UserAgent,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM auth_sessions WHERE expires_at < $1 OR revoked_at < $1
`

// Housekeeping: sessions that expired or were revoked before @before can never be used again.
// The retention window keeps recently revoked refresh tokens around for reuse detection.
func (q *Queries) DeleteExpiredSessions(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT id, user_id, created_at, last_seen_at, expires_at, revoked_at, revoke_reason, ip, user_agent FROM auth_sessions
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL AND expires_at > $3
`

type GetActiveSessionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Now    time.Time
}

func (q *Queries) GetActiveSession(ctx context.Context, arg GetActiveSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getActiveSession, arg.ID, arg.UserID, arg.Now)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.Ip,
		&i.UserAgent,
	)
	return i, err
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, email, password_hash, password_changed_at, failed_login_count, locked_until, last_login_at, created_at, updated_at FROM admin_users WHERE email = $1
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByEmail, email)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, email, password_hash, password_changed_at, failed_login_count, locked_until, last_login_at, created_at, updated_at FROM admin_users WHERE id = $1
`

func (q *Queries) GetAdminByID(ctx context.Context, id uuid.UUID) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefreshTokenForUpdate = `-- name: GetRefreshTokenForUpdate :one
SELECT
    rt.id, rt.session_id, rt.expires_at, rt.used_at,
    s.user_id, s.expires_at AS session_expires_at, s.revoked_at AS session_revoked_at
FROM refresh_tokens rt
JOIN auth_sessions s ON s.id = rt.session_id
WHERE rt.token_hash = $1
FOR UPDATE OF rt
`

type GetRefreshTokenForUpdateRow struct {
	ID               uuid.UUID
	SessionID        uuid.UUID
	ExpiresAt        time.Time
	UsedAt           *time.Time
	UserID           uuid.UUID
	SessionExpiresAt time.Time
	SessionRevokedAt *time.Time
}

// Row lock serialises concurrent refreshes of the same token.
func (q *Queries) GetRefreshTokenForUpdate(ctx context.Context, tokenHash []byte) (GetRefreshTokenForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForUpdate, tokenHash)
	var i GetRefreshTokenForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UserID,
		&i.SessionExpiresAt,
		&i.SessionRevokedAt,
	)
	return i, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO auth_audit_events (user_id, event, email, ip, user_agent, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuditEventParams struct {
	UserID    *uuid.UUID
	Event     string
	Email     *string
	Ip        *netip.Addr
	UserAgent *string
	Now       time.Time
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.UserID,
		arg.Event,
		arg.Email,
		arg.Ip,
		arg.UserAgent,
		arg.Now,
	)
	return err
}

const lockAdmin = `-- name: LockAdmin :exec
UPDATE admin_users SET locked_until = $1::timestamptz WHERE id = $2
`

type LockAdminParams struct {
	LockedUntil time.Time
	ID          uuid.UUID
}

func (q *Queries) LockAdmin(ctx context.Context, arg LockAdminParams) error {
	_, err := q.db.Exec(ctx, lockAdmin, arg.LockedUntil, arg.ID)
	return err
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :exec
UPDATE refresh_tokens SET used_at = $1::timestamptz WHERE id = $2
`

type MarkRefreshTokenUsedParams struct {
	Now time.Time
	ID  uuid.UUID
}

func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, arg MarkRefreshTokenUsedParams) error {
	_, err := q.db.Exec(ctx, markRefreshTokenUsed, arg.Now, arg.ID)
	return err
}

const recordLoginFailure = `-- name: RecordLoginFailure :one
UPDATE admin_users
SET failed_login_count = LEAST(failed_login_count + 1, 1000)
WHERE id = $1
RETURNING failed_login_count
`

// Atomic increment, so concurrent failures are all counted.
func (q *Queries) RecordLoginFailure(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, recordLoginFailure, id)
	var failed_login_count int32
	err := row.Scan(&failed_login_count)
	return failed_login_count, err
}

const recordLoginSuccess = `-- name: RecordLoginSuccess :exec
UPDATE admin_users
SET failed_login_count = 0, locked_until = NULL, last_login_at = $1::timestamptz
WHERE id = $2
`

type RecordLoginSuccessParams struct {
	Now time.Time
	ID  uuid.UUID
}

func (q *Queries) RecordLoginSuccess(ctx context.Context, arg RecordLoginSuccessParams) error {
	_, err := q.db.Exec(ctx, recordLoginSuccess, arg.Now, arg.ID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE auth_sessions SET revoked_at = $1::timestamptz, revoke_reason = $2::text
WHERE id = $3 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	Now    time.Time
	Reason string
	ID     uuid.UUID
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.Now, arg.Reason, arg.ID)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :execrows
UPDATE auth_sessions SET revoked_at = $1::timestamptz, revoke_reason = $2::text
WHERE user_id = $3 AND revoked_at IS NULL
`

type RevokeUserSessionsParams struct {
	Now    time.Time
	Reason string
	UserID uuid.UUID
}

func (q *Queries) RevokeUserSessions(ctx context.Context, arg RevokeUserSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserSessions, arg.Now, arg.Reason, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setPassword = `-- name: SetPassword :exec
UPDATE admin_users
SET password_hash = $1, password_changed_at = $2,
    failed_login_count = 0, locked_until = NULL
WHERE id = $3
`

type SetPasswordParams struct {
	PasswordHash string
	Now          time.Time
	ID           uuid.UUID
}

func (q *Queries) SetPassword(ctx context.Context, arg SetPasswordParams) error {
	_, err := q.db.Exec(ctx, setPassword, arg.PasswordHash, arg.Now, arg.ID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE auth_sessions SET last_seen_at = $1 WHERE id = $2
`

type TouchSessionParams struct {
	Now time.Time
	ID  uuid.UUID
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.Now, arg.ID)
	return err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE admin_users SET password_hash = $1 WHERE id = $2
`

type UpdatePasswordHashParams struct {
	PasswordHash string
	ID           uuid.UUID
}

// Transparent rehash on login; does not count as a password change.
func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.PasswordHash, arg.ID)
	return err
}
