// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	CountAdmins(ctx context.Context) (int64, error)
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (AdminUser, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (AuthSession, error)
	// Housekeeping: sessions that expired or were revoked before @before can never be used again.
	// The retention window keeps recently revoked refresh tokens around for reuse detection.
	DeleteExpiredSessions(ctx context.Context, before time.Time) (int64, error)
	GetActiveSession(ctx context.Context, arg GetActiveSessionParams) (AuthSession, error)
	GetAdminByEmail(ctx context.Context, email string) (AdminUser, error)
	GetAdminByID(ctx context.Context, id uuid.UUID) (AdminUser, error)
	// Row lock serialises concurrent refreshes of the same token.
	GetRefreshTokenForUpdate(ctx context.Context, tokenHash []byte) (GetRefreshTokenForUpdateRow, error)
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error
	LockAdmin(ctx context.Context, arg LockAdminParams) error
	MarkRefreshTokenUsed(ctx context.Context, arg MarkRefreshTokenUsedParams) error
	// Atomic increment, so concurrent failures are all counted.
	RecordLoginFailure(ctx context.Context, id uuid.UUID) (int32, error)
	RecordLoginSuccess(ctx context.Context, arg RecordLoginSuccessParams) error
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
	RevokeUserSessions(ctx context.Context, arg RevokeUserSessionsParams) (int64, error)
	SetPassword(ctx context.Context, arg SetPasswordParams) error
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	// Transparent rehash on login; does not count as a password change.
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error
}

var _ Querier = (*Queries)(nil)
