// Generated by scripts/extract-frames.sh — do not edit.
import type { FrameSequence } from "@/lib/frame-sequence";

export const heroFrames: FrameSequence = {
  basePath: "/frames/hero-03d38da9",
  count: 121,
  sets: {
    landscape: { width: 1600, height: 1202 },
    portrait: { width: 810, height: 1080 },
  },
};
